cp -R ./.bashrc ~

cp -R ./user-config.sh ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.bashrc

# Directory to search for .sh files
FEATURES_DIR=./features

# SHELL CONFIG FEATURES
SHELL_CONFIG_FEATURES=$HOME/.shell_config_features.sh
# wipe old configs
echo "# WARNING: This file is automatically generated. Do not edit manually." >$SHELL_CONFIG_FEATURES
sudo chmod +x $SHELL_CONFIG_FEATURES

# Search every config.sh in every directory
for file in $(find "$FEATURES_DIR" -type f -name "config.sh"); do
  echo "$file "
  cat $file >>$SHELL_CONFIG_FEATURES
done

read -p "Apply and generate the config for Xorg-server ? (y/n):" user_input

if [[ "$user_input" == "y" || "$user_input" == "Y" ]]; then

  # XINITRC
  sudo cp -R ./xinitrc ~/.xinitrc
  sed -i '2i # WARNING: This file is automatically generated. Do not edit manually.' ~/.xinitrc

  # XRESOURCES
  sudo mkdir -p $HOME/.config/X11
  sudo cp -R ./Xresources ~/.config/X11/Xresources
  sudo sed -i "1i #include \"$HOME/.config/X11/Xresources_config_features\"" ~/.config/X11/Xresources
  sudo sed -i '1i !! WARNING: This file is automatically generated. Do not edit manually.' ~/.config/X11/Xresources

  # XRESOURCES CONFIG FEATURES
  XRESOURCES_CONFIG_FEATURES=$HOME/.config/X11/Xresources_config_features
  sudo echo "!! WARNING: This file is automatically generated. Do not edit manually." | sudo tee $XRESOURCES_CONFIG_FEATURES >/dev/null

  # Search every Xresources.txt in every directory
  for file in $(find "$FEATURES_DIR" -type f -name "Xresources"); do
    sudo echo "$file "
    sudo cat $file | sudo tee -a $XRESOURCES_CONFIG_FEATURES >/dev/null
  done
fi
echo "These reload command already copied to your clipboard: source ~/.bashrc; xrdb ~/.config/X11/Xresources; tmux source ~/.tmux.conf"
echo "source ~/.bashrc; xrdb ~/.config/X11/Xresources; tmux source ~/.tmux.conf" | xclip -selection clipboard
