cp -R ./.bashrc ~

sudo mkdir -p $HOME/.config/X11
sudo cp -R ./Xresources ~/.config/X11/Xresources

cp -R ./user-config.sh ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.bashrc

sudo sed -i "1i #include \"$HOME/.config/X11/Xresources_config_features\"" ~/.config/X11/Xresources
sudo sed -i '1i !! WARNING: This file is automatically generated. Do not edit manually.' ~/.config/X11/Xresources
