cp -R ./.bashrc ~
cp -R ./user-config.sh ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.user-config.sh
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.bashrc
