# Directory to search for .sh files
FEATURES_DIR=./features
SHELL_CONFIG_FEATURES=$HOME/.shell_config_features.sh

# wipe old configs
echo "# WARNING: This file is automatically generated. Do not edit manually." >$SHELL_CONFIG_FEATURES
sudo chmod +x $SHELL_CONFIG_FEATURES

# Search every config.sh in every directory
for file in $(find "$FEATURES_DIR" -type f -name "config.sh"); do
  echo "$file "
  cat $file >>$SHELL_CONFIG_FEATURES
done

XRESOURCES_CONFIG_FEATURES=$HOME/.config/X11/Xresources_config_features
# wipe old configs
sudo echo "!! WARNING: This file is automatically generated. Do not edit manually." | sudo tee $XRESOURCES_CONFIG_FEATURES >/dev/null

# Search every Xresources.txt in every directory
for file in $(find "$FEATURES_DIR" -type f -name "Xresources"); do
  sudo echo "$file "
  sudo cat $file | sudo tee -a $XRESOURCES_CONFIG_FEATURES >/dev/null
done
